version: "3.7"
services:
  node:
    image: ghcr.io/subspace/node:gemini-1b-2022-jun-13
    volumes:
      - node-data:/var/subspace:rw
    ports:
      - "0.0.0.0:30333:30333"
    restart: unless-stopped
    command: [
      "--chain", "gemini-1",
      "--base-path", "/var/subspace",
      "--execution", "wasm",
      "--pruning", "archive",
      "--listen-addr", "/ip4/0.0.0.0/tcp/30333",
      "--in-peers", "2000",
      "--in-peers-light", "2000",
      "--out-peers", "1000",
      "--reserved-nodes", "/dns/bootstrap-9.gemini-1b.subspace.network/tcp/30333/p2p/12D3KooWNGxWQ4sajzW1akPRZxjYM5TszRtsCnEiLhpsGrsHrFC6",
      "--reserved-only",
    ]
    healthcheck:
      timeout: 5s
# If node setup takes longer then expected, you want to increase `interval` and `retries` number.
      interval: 30s
      retries: 5
volumes:
  node-data: